name = str(input("Enter your name: "))
age = int(input("Enter your age :"))
course_code = int(input("Enter your course code:"))
print(name,age,course_code)
print(type(name))
print(type(age))
print(type(course_code))